import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  buildAgentSkillCommandTable,
  type OpenApiDocument
} from "../src/agent-skill-reference.js";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const contractDir = resolve(scriptDir, "..");
const repoRoot = resolve(contractDir, "..", "..");
const openApiPath = resolve(contractDir, "openapi.json");
const referencePath = resolve(
  repoRoot,
  "agent-skills/perennia/references/api-operations.md"
);

const COMMAND_START_MARKER = "<!-- GENERATED:command-map:start -->";
const COMMAND_END_MARKER = "<!-- GENERATED:command-map:end -->";

const document = JSON.parse(
  await readFile(openApiPath, "utf8")
) as OpenApiDocument;
const table = buildAgentSkillCommandTable(document);

const generatedBlock = [
  COMMAND_START_MARKER,
  "<!-- Generated by packages/contract/scripts/generate-agent-skill-reference.ts",
  "     from packages/contract/openapi.json. Do not edit this block by hand;",
  "     run `corepack pnpm --filter @perennia/contract run generate`. -->",
  "",
  "| Command | Method | Path |",
  "|---|---:|---|",
  ...table.map(
    (row) => `| \`${row.command}\` | ${row.method} | \`${row.path}\` |`
  ),
  COMMAND_END_MARKER
].join("\n");

const existing = await readFile(referencePath, "utf8");
await writeFile(
  referencePath,
  replaceMarkedBlock({
    content: existing,
    endMarker: COMMAND_END_MARKER,
    filePath: referencePath,
    generatedBlock,
    startMarker: COMMAND_START_MARKER
  }),
  "utf8"
);

function replaceMarkedBlock({
  content,
  endMarker,
  filePath,
  generatedBlock,
  startMarker
}: {
  content: string;
  endMarker: string;
  filePath: string;
  generatedBlock: string;
  startMarker: string;
}): string {
  const startIndex = content.indexOf(startMarker);
  const endIndex = content.indexOf(endMarker);

  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
    throw new Error(
      `${filePath} is missing a valid ${startMarker} / ${endMarker} generated block.`
    );
  }

  return (
    content.slice(0, startIndex) +
    generatedBlock +
    content.slice(endIndex + endMarker.length)
  );
}
